version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: turborepo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: turborepo_dev
      MYSQL_USER: developer
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: turborepo-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: developer
      PMA_PASSWORD: dev123
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy

  php-app:
    build:
      context: ./apps/web-php
      dockerfile: Dockerfile
    container_name: turborepo-php-app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: turborepo_dev
      DB_USERNAME: developer
      DB_PASSWORD: dev123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ENV: development
      APP_TIMEZONE: Asia/Shanghai
    ports:
      - "3005:80"
    volumes:
      - ./apps/web-php:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: turborepo-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 3s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: turborepo-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:redis123
      HTTP_USER: admin
      HTTP_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy

  python-api:
    build:
      context: ./apps/api-python
      dockerfile: Dockerfile
    container_name: turborepo-python-api
    restart: unless-stopped
    environment:
      PORT: 3003
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: turborepo_dev
      DB_USERNAME: developer
      DB_PASSWORD: dev123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
    ports:
      - "3003:3003"
    volumes:
      - ./apps/api-python:/app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local